// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACKkwUdXX2-XoDhTJXNmZ_sRGhOGbBhyI',
    appId: '1:148291436448:web:dcc544bae087db30d1eec5',
    messagingSenderId: '148291436448',
    projectId: 'power-house-gym-4fe99',
    authDomain: 'power-house-gym-4fe99.firebaseapp.com',
    storageBucket: 'power-house-gym-4fe99.firebasestorage.app',
    measurementId: 'G-3DN4GZDL6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rhe6ptYCTEMaW4Qzmr2UGvIww49KTbw',
    appId: '1:148291436448:android:f4cd70ff22147990d1eec5',
    messagingSenderId: '148291436448',
    projectId: 'power-house-gym-4fe99',
    storageBucket: 'power-house-gym-4fe99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsYdu5sE4xEpJ3rDfthsrrH8NFaATn9ls',
    appId: '1:148291436448:ios:fe23de1bc14ba0d7d1eec5',
    messagingSenderId: '148291436448',
    projectId: 'power-house-gym-4fe99',
    storageBucket: 'power-house-gym-4fe99.firebasestorage.app',
    iosBundleId: 'com.example.powerGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsYdu5sE4xEpJ3rDfthsrrH8NFaATn9ls',
    appId: '1:148291436448:ios:fe23de1bc14ba0d7d1eec5',
    messagingSenderId: '148291436448',
    projectId: 'power-house-gym-4fe99',
    storageBucket: 'power-house-gym-4fe99.firebasestorage.app',
    iosBundleId: 'com.example.powerGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACKkwUdXX2-XoDhTJXNmZ_sRGhOGbBhyI',
    appId: '1:148291436448:web:34e0bd31ffe671d2d1eec5',
    messagingSenderId: '148291436448',
    projectId: 'power-house-gym-4fe99',
    authDomain: 'power-house-gym-4fe99.firebaseapp.com',
    storageBucket: 'power-house-gym-4fe99.firebasestorage.app',
    measurementId: 'G-4LDS8MBGT5',
  );
}
